[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
board_build.partitions = partitions/partitions_ota.csv
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    tzapu/WiFiManager@^2.0.17
    RemoteDebug@^4.0.0
