from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

esp32s3_lifelog_sklib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'ESP32-S3-WROOM-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-S3-WROOM-1'}), 'ref_prefix':'U', 'fplist':['RF_Module:ESP32-S3-WROOM-1'], 'footprint':'RF_Module:ESP32-S3-WROOM-1U', 'keywords':'RF Radio BT ESP ESP32-S3 Espressif onboard PCB antenna', 'description':'RF Module, ESP32-S3 SoC, Wi-Fi 802.11b/g/n, Bluetooth, BLE, 32-bit, 3.3V, onboard antenna, SMD', 'datasheet':'https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='3V3',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='IO4',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='IO5',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='IO6',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='IO7',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='IO15',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='IO16',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='IO17',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='IO18',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='IO8',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='USB_D-',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='USB_D+',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='IO3',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='IO46',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='IO9',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='IO10',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='IO11',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='IO12',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='IO13',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='IO14',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='IO21',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='IO47',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='IO48',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='IO45',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='IO0',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='IO35',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='IO36',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='IO37',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='IO38',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='IO39',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='IO40',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='IO41',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='IO42',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='RXD0',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='TXD0',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='IO2',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='IO1',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='41',name='GND',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x24', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x24'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_FFC-FPC:Hirose_FH12-24S-0.5SH_1x24-1MP_P0.50mm_Horizontal', 'keywords':'connector', 'description':'Generic connector, single row, 01x24, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='Pin_17',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='Pin_18',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='Pin_19',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='Pin_20',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='Pin_21',func=pin_types.PASSIVE,unit=1),
            Pin(num='22',name='Pin_22',func=pin_types.PASSIVE,unit=1),
            Pin(num='23',name='Pin_23',func=pin_types.PASSIVE,unit=1),
            Pin(num='24',name='Pin_24',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MMICT390200012', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MMICT390200012'}), 'ref_prefix':'MIC', 'fplist':['T3902:MIC-SMD_5P-L3.5-W2.7-TL_MMICT390200012'], 'footprint':'T3902:MIC-SMD_5P-L3.5-W2.7-TL_MMICT390200012', 'keywords':'MEMS Microphones', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C3171752.pdf', 'pins':[
            Pin(num='1',name='DATA',func=pin_types.UNSPEC),
            Pin(num='2',name='SELECT',func=pin_types.UNSPEC),
            Pin(num='4',name='CLK',func=pin_types.UNSPEC),
            Pin(num='5',name='VDD',func=pin_types.UNSPEC),
            Pin(num='3',name='GND',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'MAX17048G+T10', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MAX17048G+T10'}), 'ref_prefix':'U', 'fplist':['MAX17048:TDFN-8_L2.0-W2.0-P0.50-BL-EP1.2'], 'footprint':'MAX17048:TDFN-8_L2.0-W2.0-P0.50-BL-EP1.2', 'keywords':'Battery Management ICs', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C2682616.pdf', 'pins':[
            Pin(num='1',name='CTG',func=pin_types.UNSPEC),
            Pin(num='2',name='CELL',func=pin_types.UNSPEC),
            Pin(num='3',name='VDD',func=pin_types.UNSPEC),
            Pin(num='4',name='GND',func=pin_types.UNSPEC),
            Pin(num='5',name='~{ALRT}',func=pin_types.UNSPEC),
            Pin(num='6',name='QSTRT',func=pin_types.UNSPEC),
            Pin(num='7',name='SCL',func=pin_types.UNSPEC),
            Pin(num='8',name='SDA',func=pin_types.UNSPEC),
            Pin(num='9',name='EP',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'CH224K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CH224K'}), 'ref_prefix':'U', 'fplist':['CH224K:ESSOP-10_L4.9-W3.9-P1.0-LS6.0-TL-EP'], 'footprint':'CH224K:ESSOP-10_L4.9-W3.9-P1.0-LS6.0-TL-EP', 'keywords':'USB ICs', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C970725.pdf', 'pins':[
            Pin(num='1',name='VDD',func=pin_types.UNSPEC),
            Pin(num='2',name='CFG2',func=pin_types.UNSPEC),
            Pin(num='3',name='CFG3',func=pin_types.UNSPEC),
            Pin(num='4',name='DP',func=pin_types.UNSPEC),
            Pin(num='5',name='DM',func=pin_types.UNSPEC),
            Pin(num='6',name='CC2',func=pin_types.UNSPEC),
            Pin(num='7',name='CC1',func=pin_types.UNSPEC),
            Pin(num='8',name='VBUS',func=pin_types.UNSPEC),
            Pin(num='9',name='CFG1',func=pin_types.UNSPEC),
            Pin(num='10',name='PG',func=pin_types.UNSPEC),
            Pin(num='11',name='GND',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'BQ25895RTW', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BQ25895RTW'}), 'ref_prefix':'U', 'fplist':['Package_DFN_QFN:Texas_RTW_WQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias'], 'footprint':'Package_DFN_QFN:Texas_RTW_WQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias', 'keywords':'1-cell Battery-Charger Power-Path-Management OTG', 'description':'I2C Controlled Single Cell (Li-Ion / Li-Polymer) 5A Fast Charger with MaxCharge, USB BC1.2 Detection, 3.9..14V VBUS, 3.840..4.608V charge voltage range, 1.5 MHz (buck mode) and 500 kHz /1.5 MHz (boost mode), WQFN-24', 'datasheet':'http://www.ti.com/lit/ds/symlink/bq25895.pdf', 'pins':[
            Pin(num='1',name='VBUS',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='STAT',func=pin_types.OPENCOLL,unit=1),
            Pin(num='5',name='SCL',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='SDA',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='~{INT}',func=pin_types.OPENCOLL,unit=1),
            Pin(num='8',name='OTG',func=pin_types.INPUT,unit=1),
            Pin(num='9',name='~{CE}',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='ILIM',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='TS',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='~{QON}',func=pin_types.INPUT,unit=1),
            Pin(num='13',name='BAT',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='BAT',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='SYS',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='SYS',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='18',name='PGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='SW',func=pin_types.PWROUT,unit=1),
            Pin(num='20',name='SW',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='BTST',func=pin_types.PASSIVE,unit=1),
            Pin(num='22',name='REGN',func=pin_types.PWROUT,unit=1),
            Pin(num='23',name='PMID',func=pin_types.PWROUT,unit=1),
            Pin(num='24',name='DSEL',func=pin_types.OPENCOLL,unit=1),
            Pin(num='25',name='PGND',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'Inductor_SMD:L_1210_3225Metric', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_JST:JST_PH_B2B-PH-K_1x02_P2.00mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'DMP3013SFV', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DMP3013SFV'}), 'ref_prefix':'Q', 'fplist':['Package_SON:Diodes_PowerDI3333-8'], 'footprint':'Package_SON:Diodes_PowerDI3333-8', 'keywords':'P-Channel MOSFET', 'description':'-12A Id, -30V Vds, P-Channel Power MOSFET, 9.5mOhm Ron, 33.7nC Qg (typ), PowerDI3333-8', 'datasheet':'https://www.diodes.com/assets/Datasheets/DMP3013SFV.pdf', 'pins':[
            Pin(num='1',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TPS63020DSJR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS63020DSJR'}), 'ref_prefix':'U', 'fplist':['TPS63020:VSON-14_L4.0-W3.0-P0.50-BL-EP_TI_DSJ'], 'footprint':'TPS63020:VSON-14_L4.0-W3.0-P0.50-BL-EP_TI_DSJ', 'keywords':'DC-DC Converters', 'description':'', 'datasheet':'https://lcsc.com/product-detail/DC-DC-Converters_TI_TPS63020DSJR_TPS63020DSJR_C15483.html', 'pins':[
            Pin(num='1',name='VINA',func=pin_types.UNSPEC),
            Pin(num='2',name='GND',func=pin_types.UNSPEC),
            Pin(num='3',name='FB',func=pin_types.UNSPEC),
            Pin(num='4',name='VOUT',func=pin_types.UNSPEC),
            Pin(num='5',name='VOUT',func=pin_types.UNSPEC),
            Pin(num='6',name='L2',func=pin_types.UNSPEC),
            Pin(num='7',name='L2',func=pin_types.UNSPEC),
            Pin(num='8',name='L1',func=pin_types.UNSPEC),
            Pin(num='9',name='L1',func=pin_types.UNSPEC),
            Pin(num='10',name='VIN',func=pin_types.UNSPEC),
            Pin(num='11',name='VIN',func=pin_types.UNSPEC),
            Pin(num='12',name='EN',func=pin_types.UNSPEC),
            Pin(num='13',name='PS/SYNC',func=pin_types.UNSPEC),
            Pin(num='14',name='PG',func=pin_types.UNSPEC),
            Pin(num='15',name='PGND',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'AP2127K-2.8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2127K-2.8'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'linear regulator ldo fixed positive', 'description':'300mA low dropout linear regulator, shutdown pin, 2.5V-6V input voltage, 2.8V fixed positive output, SOT-23-5', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP2127.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AP2127K-1.8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2127K-1.8'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'linear regulator ldo fixed positive', 'description':'300mA low dropout linear regulator, shutdown pin, 2.5V-6V input voltage, 1.8V fixed positive output, SOT-23-5', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP2127.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AP2127K-1.5', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2127K-1.5'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'linear regulator ldo fixed positive', 'description':'300mA low dropout linear regulator, shutdown pin, 2.5V-6V input voltage, 1.5V fixed positive output, SOT-23-5', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP2127.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Micro_SD_Card_Det2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Micro_SD_Card_Det2'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Card:microSD_HC_Hirose_DM3AT-SF-PEJM5', 'keywords':'connector SD microsd', 'description':'Micro SD Card Socket with two card detection pins', 'datasheet':'https://www.hirose.com/en/product/document?clcode=&productname=&series=DM3&documenttype=Catalog&lang=en&documentid=D49662_en', 'pins':[
            Pin(num='1',name='DAT2',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='DAT3/CD',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='CMD',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='CLK',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='DAT0',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='DAT1',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='DET_B',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='DET_A',func=pin_types.PASSIVE,unit=1),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USB_C_Receptacle_USB2.0_16P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle_USB2.0_16P'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12', 'keywords':'usb universal serial bus type-C USB2.0', 'description':'USB 2.0-only 16P Type-C Receptacle connector', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='A6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='A7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR,unit=1),
            Pin(num='A9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='B6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR,unit=1),
            Pin(num='B9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':[''], 'footprint':'Button_Switch_SMD:SW_SPST_TL3342', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, two pins', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0805_2012Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])