name: PR Check sa-only permissions
on:
  workflow_call:
    inputs:
      component:
        description: 'Component'
        required: false
        default: 'server'
        type: string
jobs:
  py:
    if: inputs.component == 'server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: echo done
  sa:
    if: inputs.component == 'security'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: |
            python
            javascript
      - uses: github/codeql-action/analyze@v3
      - run: echo done
