name: PR Check with inputs
on:
  workflow_call:
    inputs:
      component:
        description: 'Component'
        required: false
        type: string
        default: 'server'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.component }}
