name: Test pr-check with if gates
on:
  workflow_call:
    inputs:
      component:
        description: 'Component'
        required: false
        default: 'server'
        type: string
jobs:
  py:
    if: inputs.component == 'server'
    runs-on: ubuntu-latest
    steps:
      - run: echo py ${{ inputs.component }}
  db:
    if: inputs.component == 'dashboard'
    runs-on: ubuntu-latest
    steps:
      - run: echo db ${{ inputs.component }}
